name: Clone Another Repo

on:
  workflow_dispatch:
    inputs:
      repo_to_clone:
        description: 'Full name of the repo to clone (e.g. org/repo)'
        default: "iladin/dotfiles"

jobs:
  run-kics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_to_clone }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./${{ github.event.inputs.repo_to_clone }}
      - name: Mkdir results-dir
      # make sure results dir is created
        run: mkdir -p ./${{ github.event.inputs.repo_to_clone }}/myResults
      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v1.7.0
        with:
          # path to file or directory to scan
          path: ./${{ github.event.inputs.repo_to_clone }}
          # file path to store result in json format
          output_path: myResults
          # file path to store source internal representation in JSON format
          payload_path: # optional
          # path to directory with queries (default "./assets/queries")
          queries: # optional
          # verbose scan
          verbose: # optional