name: Run KICS on remote repo

on:
  workflow_dispatch:
    inputs: 
      repo_to_clone:
        description: 'Full name of the repo to clone (e.g. org/repo)'
        default: "iladin/dotfiles"
jobs:
  run-kics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_to_clone }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./${{ github.event.inputs.repo_to_clone }}
      - name: Mkdir results-dir
      # make sure results dir is created
        run: mkdir -p ./${{ github.event.inputs.repo_to_clone }}/myResults
      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v1.7.0
        with:
          # path to file or directory to scan
          path: ./${{ github.event.inputs.repo_to_clone }}
          # file path to store result in json format
          output_path: myResults
          # Add in html report
          output_formats: 'json,sarif,html'
          # defines which non-zero exit codes should be ignored (all, results, errors, none)
          ignore_on_exit: results
          # file path to store source internal representation in JSON format
          payload_path: # optional
          # path to directory with queries (default "./assets/queries")
          queries: # optional
          # verbose scan
          verbose: # optional
      - run: find ./${{ github.event.inputs.repo_to_clone }} myResults -type f # -name "*.json" -exec jq -c . {} \; > ./${{ github.event.inputs.repo_to_clone }}/myResults/results.json
      - name: Upload KICS SARIF report
        uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47
        with:
          sarif_file: ./${{ github.event.inputs.repo_to_clone }}/myResults/results.sarif

      - name: Upload KICS HTML report
        uses: actions/upload-artifact@v4
        with:
          name: kics-html-report
          path: ./${{ github.event.inputs.repo_to_clone }}/myResults/results.html